### ISSUE TITLE
Option: direction: 'right'

### ISSUE THREAD

**Issue by SixSatori** [pencilpix/bs.push.nav#1]
Option: direction: 'right' is not working.
the css part is alright.
when i change the default option inside the main.js  to 'right' it works:

example:
  var defaults    = {
                      breakpoint: 768,
                      typeClass: 'slide',
                      direction: 'right',
                      targetsList: [],
                      templates: {},
                      bodyWrapper: '#wrapper'
                    };

**Comment by pencilpix** [comment]
@SixSatori 
If you are using `data-toggle="bsPushNav"` in the same time when you are using manual init for the plugin, the options that set using the `data` attribute initialization will override the options you install it manually, so please use only one of the 2 ways so that you can init the plugin

example

```
<button type="button" class="navbar-toggle">
   <span class="sr-only">Toggle navigation</span>
   <span class="icon-bar"></span>
   <span class="icon-bar"></span>
   <span class="icon-bar"></span>
</button>


<script>
    $(document).ready(function() {
      $('.navbar-toggle').bsPushNav({
        breakpoint: 800,
        direction: 'left',
        typeClass: 'push',
        targetsList: ['#menu1', '#menu2']
      });
    });
</script>
```

or you can use this way to init:

```
<button type="button" class="navbar-toggle" data-toggle="bsPushNav" data-breakpoint="800" data-direction="right" data-type="push" data-target="#menu1 #menu2">
  <span class="sr-only">Toggle navigation</span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</button>
```
